"""add patient table

Revision ID: 54dff7cd4a4e
Revises: 3ac4bfc54cd8
Create Date: 2023-03-14 17:28:51.165372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54dff7cd4a4e'
down_revision = '3ac4bfc54cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('identification_number', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_patient_identification_number'), 'patient', ['identification_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_identification_number'), table_name='patient')
    op.drop_column('patient', 'identification_number')
    # ### end Alembic commands ###
